@baseUrl= http://localhost:3000/api
@orderId = 717d7e24-8a7a-4429-8349-b4e5d3a406bf
@status = PENDING
@newStatus = DELIVERED

# @name getOrders
GET {{baseUrl}}/orders
    ?page=1
    &limit=10
    # &status=DELIVERED
Content-Type: application/json

###

# @name getOrder
GET {{baseUrl}}/orders/id/{{orderId}}
Content-Type: application/json

###

# @name getOrdersByStatus
GET {{baseUrl}}/orders/{{status}}
Content-Type: application/json

###

# @name createOrder
POST {{baseUrl}}/orders
Content-Type: application/json

{
    "items": [
        {
            "productId": 4,
            "price": 0,
            "quantity": 1
        },
        {
            "productId": 5,
            "price": 0,
            "quantity": 1
        }
    ]
}

###

# @name updateOrderStatus
PATCH {{baseUrl}}/orders/{{orderId}}
Content-Type: application/json

{
    "status": "{{newStatus}}"
}
