@baseUrl= http://localhost:3000/api
@orderId = 0dc6cb0c-0441-4888-a43b-e6dac7eaaf65
@status = PENDING
@newStatus = DELIVERED

# @name getOrders
GET {{baseUrl}}/orders
    ?page=1
    &limit=10
    # &status=DELIVERED
Content-Type: application/json

###

# @name getOrder
GET {{baseUrl}}/orders/id/{{orderId}}
Content-Type: application/json

###

# @name getOrdersByStatus
GET {{baseUrl}}/orders/{{status}}
Content-Type: application/json

###

# @name createOrder
POST {{baseUrl}}/orders
Content-Type: application/json

{
    "items": [
        {
            "productId": 5,
            "price": 100,
            "quantity": 8
        },
        {
            "productId": 8,
            "price": 100,
            "quantity": 2
        }
    ]
}

###

# @name updateOrderStatus
PATCH {{baseUrl}}/orders/{{orderId}}
Content-Type: application/json

{
    "status": "{{newStatus}}"
}
