@stripeSignature=

###
# @name healthCheck
GET {{paymentsHost}}

###
# @name paymentsSuccess
GET {{paymentsHost}}/payments/success

###
# @name paymentsCancel
GET {{paymentsHost}}/payments/cancel

###
# @name stripeWebhook
POST {{paymentsHost}}/payments/webhook
Content-Type: application/json
stripe-signature: {{stripeSignature}}

{
  "id": "evt_test_webhook",
  "object": "event",
  "type": "charge.succeeded",
  "data": {
    "object": {
      "id": "ch_test_123",
      "metadata": {
        "orderId": "order_test_123"
      },
      "receipt_url": "https://example.com/receipt"
    }
  }
}
